### ISSUE TITLE
PBR doesn't pause on a blank screen between matches

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pbrEngine#11]
The emulator is on a black screen after the match ends, but is suddenly in a menu when it pauses.

**Comment by Felk** [comment]
silly alternative solution would be to have the hex background fade to a little less black so it doesn't reach the opacity value in the corners

**Comment by m4-used-rollout** [comment]
That's not a solution. It wouldn't fix PBR being visible behind the sidegame. PBR needs to sit on a black screen between matches if at all possible.

**Comment by Felk** [comment]
oh, okay. iirc it used to work by pausing during the loading screen after a match. not sure what changed

**Comment by ghost** [comment]
Expecting this to be resolved by bffdfba17cabee5d2a9d4033925c9f599f320a76

**Comment by ghost** [comment]
Worth noting that PBR will still pause on the colorful battle menu screen prior to the very first match.  But after that, it will sit on black between matches.

**Comment by ghost** [comment]
Resolution successful
