### ISSUE TITLE
First turn is a forced and instantaneous move A selection

### ISSUE THREAD

**Issue by ferraro1** [TwitchPlaysPokemon/pbrEngine#4]
I suspect this is a pbrengine issue, but it might be the tpp core's fault instead.
https://clips.twitch.tv/VenomousInventiveTaroDoritosChip

The first move selection is an instantaneous A, but the tpp core is expected to wait ~5 seconds before making the selection, and no-one is on move A so it should never have been selected.

**Comment by Felk** [comment]
My guess is its pbrengine's fault:

the "state" changes to in-battle after the first move selection appears. before that, the "unstucker" is still active, which repeats the previous button if nothing happened (~no state change or similar~ correction: no input performed) for some hardcoded time. i widely increased that value somewhen to account for very long startup animations and the sort, like regigiga's slow start popup. but maybe that just isn't done right and the unstucker happens to still randomly press A at that moment

**Comment by Felk** [comment]
see also https://github.com/TwitchPlaysPokemon/pbrEngine/blob/master/pbrEngine/engine.py#L455

apparently the time isn't "widely increased" as I thought. so I guess this glitch is just a matter of the gui popping up at a multiple of 300 frames

**Comment by ferraro1** [comment]
Thanks, I'll check the unstucker behavior

**Comment by ghost** [comment]
Issue never occurred again after the doubles update
